networks:
  FinanceNetwork:
    driver: bridge

services:
  lab4:
    image: lab4
    build:
      context: .
      dockerfile: Lab4/Dockerfile
    working_dir: "/app"
    ports:
      - "5000:80"
    networks:
        - FinanceNetwork
    depends_on: 
      finance-postgres:
        condition: service_healthy
  
  finance-postgres:
    image: postgres
    container_name: finance-postgres
    environment:
      POSTGRES_USER: postgres_finance
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FinanceDb
    networks: 
      - FinanceNetwork
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_finance -d FinanceDb" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./FinanceDb:/var/lib/postgresql/data
